### ISSUE TITLE
Toastr not working on laravel 5.8

### ISSUE THREAD

**Issue by aaron-za-dev** [DashboardPack/architectui-html-theme-free#1]
The included js and css files available in the repository, but when testing from a blade view does not work.

Since the components-notifications.html file works fine, I tried to rebuild the files with npm run build and I get the same error.

![tstr](https://user-images.githubusercontent.com/16365508/64521261-55b3a800-d2bd-11e9-9e33-ba95f4b7b344.PNG)

![msg](https://user-images.githubusercontent.com/16365508/64521277-5b10f280-d2bd-11e9-9ed0-9a7f39e75d0a.PNG)

![demo](https://user-images.githubusercontent.com/16365508/64521787-3d905880-d2be-11e9-91a3-9259e1bcffd2.PNG)

**Comment by shw2ypro** [comment]
I have the same issue here

**Comment by sublimedatasys** [comment]
@aaron-za-dev @shw2ypro 

Hello,
Can you please verify path in file included properly or not because as per Toastr main page they are supporting laravel 5.5
Also please check if file is imported in your blade html template correctly?

**Comment by sar0z** [comment]
Did anyone solve the issue?

**Comment by Dreller** [comment]
Just hit that too, anyone found a workaround?

**Comment by Mehonder** [comment]
1- Find this row at main.js
        void 0 === ( a = function (t) {
            return function () { 
                var e,
                i,
                n,
                a = 0,
                r = {
                    error: "error",
                    info: "info",
                    success: "success",
                    warning: "warning"
                },
 2- Add variable befor a 
        void 0 === ( **window.$ACT_TOASTR =** a = function (t) {
            return function () { 
                var e,
                i,
                n,
                a = 0,
                r = {
                    error: "error",
                    info: "info",
                    success: "success",
                    warning: "warning"
                },
