### ISSUE TITLE
ArchitectUI Dashboard HTML PRO - Personal License installation issue

### ISSUE THREAD

**Issue by sergeoken** [DashboardPack/architectui-html-theme-free#14]
Hi sir

1 - I purshased the ArchitectUI Dashboard HTML PRO - Personal License and i try to install it and i have this error

![image](https://user-images.githubusercontent.com/42818492/85632737-c3c03480-b66f-11ea-900d-775aa214214a.png)

Please can you help me fixe the problem.

2 - it is possible to use your HTML PRO in angular project ? 

Thanks

Serge

**Comment by DPTeamMember** [comment]
Hello @sergeoken 

1. We have resolved the installation issue in our new update, please check the private repo of ArchitectUI Dashboard HTML PRO.
2. We have a separate ArchitectUI Template for angular. You can check it here https://dashboardpack.com/bootstrap-templates/angular-themes/

Thank you.
