### ISSUE TITLE
Settings and Theme Colours

### ISSUE THREAD

**Issue by willsmithbsc** [DashboardPack/architectui-html-theme-free#15]
Just a quick question, when i open the settings cog and choose my colour palette, how do i make the change permanent and remove the cog.

HTML version

**Comment by levilliard** [comment]
If you want to change the sidebar theme you can use `bg-secondary` and `sidebar-text-light` like below:
`<div class="app-main">
     <div class="app-sidebar sidebar-shadow bg-secondary sidebar-text-light">
      ....
     </div>
 </div>
`

**Comment by DPTeamMember** [comment]
Hello @levilliard 

We appreciate your help.

Thank you.
