### ISSUE TITLE
Scrollbar is missing.

### ISSUE THREAD

**Issue by rknidzam** [DashboardPack/architectui-html-theme-free#16]
Hi, 
I just integrate integrate ArchitectUI with DevExpress, somehow the scrollbar is missing.
Is there any settings need to be modified/edited for the Left Menu Scrollbar?

Thanks

**Comment by DPTeamMember** [comment]
Hello @rknidzam 

There is no additional setting for Left Menu Scrollbar, main.js, and main.css files are enough to get it to work.

Thank you.
