### ISSUE TITLE
Anyone using there themes?

### ISSUE THREAD

**Issue by twf-nikhila** [DashboardPack/architectui-html-theme-free#19]
Hello,

I want to ask if anyone is using their pro theme, it looks like there support team don't answer. Can anyone provide some feedback?

**Comment by mcgoode** [comment]
I am considering purchasing but they have yet to message me on Facebook or reply to my email send via their support form. Which is not a great sign that I should give them our money.

**Comment by DPTeamMember** [comment]
Hello @twf-nikhila @mcgoode 

For support, you can use our website https://dashboardpack.com/
You will get your issue resolved within 24 hrs. We were not active on the git hub but will be available from now.

Thank you.
