### ISSUE TITLE
How to edit the CSS file

### ISSUE THREAD

**Issue by sheetaltg** [DashboardPack/architectui-html-theme-free#2]
Hi,
In the CSS file it is mentioned as "DON'T EDIT THE CSS FILE DIRECTLY, since it is automatically generated from the LESS templates."

I just wanted to know how to edit the CSS file ?

**Comment by sublimedatasys** [comment]
Hi @sheetee 

You can change the SCSS file which you can find inside src/assets/ path. 
This files than converted into css file at run time. So you can change styling in SCSS file only.

Thank you.
