### ISSUE TITLE
ChartJS in the free pack

### ISSUE THREAD

**Issue by mgsphdev** [DashboardPack/architectui-html-theme-free#22]
Hello, i could not find the steps on how to edit the charts in Architect UI HTML free pack. Can you please help or point me on the right direction? Many thanks!

**Comment by DPTeamMember** [comment]
Hello @mgsphdev 

Please follow the path "architectui-html-theme-free\src\scripts-init\charts". Here you will get all the .js files for chats.
You can edit these files according to your need. 
For more information about the chart we are using, you can check the official documentation of the chart library.
Library document URL - https://www.chartjs.org/docs/latest/

Thank you.
