### ISSUE TITLE
Hide sidebar by default

### ISSUE THREAD

**Issue by mrzewnicki** [DashboardPack/architectui-html-theme-free#24]
Hi,

i faced with problem to set hide sidebar as default. In my system user can change in profile preferences does he want always display it or not.

I tred add closed-sidebar class to line below from backend
![image](https://user-images.githubusercontent.com/21024857/108219210-ca874480-7135-11eb-8685-7a473421c21f.png)

but with any reload it's looks like some js remove this class automaticly and expand side bar. I wrote js func to await for example 2 sec and then add this class and it's work but that isn't my point how should it work.  It's prove that something manage it but i cannot find  what. 

When i reload page with Ctrl+F5 clearing cache i see this class in inspector for a second and then something remove it.

Does anyone faced with similar issue? Any solution you found?

**Comment by DPTeamMember** [comment]
Hello @mrzewnicki 

Please check the file "architectui-html-theme-free\src\app.js" in this file find resizeClass function.
`var resizeClass = function () {
        var win = document.body.clientWidth;
        if (win < 1250) {
            $('.app-container').addClass('closed-sidebar-mobile closed-sidebar');
        } else {
            $('.app-container').removeClass('closed-sidebar-mobile closed-sidebar');
        }
    };`
    
The above code is responsible for adding and removing the "closed-sidebar" class. 
You can change the if condition or the entire function according to your need. 
This will resolve your issue.
    
Thank you.
