### ISSUE TITLE
Issue in  free HTML version console

### ISSUE THREAD

**Issue by gautamvishnu** [DashboardPack/architectui-html-theme-free#26]
I am just trying free HTML version but browser displaying an error every time in console.

![image](https://user-images.githubusercontent.com/62509840/119952665-e3b45280-bfba-11eb-932c-c6cddef4f0c4.png)

**Comment by DPTeamMember** [comment]
Hello @gautamvishnu 

Are you using the latest updated version of the template? We have updated the template a few days back.
I tested the template as you mentioned but not facing such an error. If this error accords after some modification, please share the modified code.

Thank you.
