### ISSUE TITLE
Search box from Select2 Single not working inside the modals - Pro Version

### ISSUE THREAD

**Issue by italolemos** [DashboardPack/architectui-html-theme-free#28]
I had to use  a select2 single input inside the modal but the search feature is blocked. I can't typing anything inside de search box as you see in the imagem below. The pointer does not appear as when I use the select2 outside the modal.

![image](https://user-images.githubusercontent.com/8310717/129081715-42a9a381-f3ac-4cc7-aafd-bc49823738de.png)

**Comment by DPTeamMember** [comment]
Hello @italolemos 

Please share a code snippet, It will help us to understand the issue.

Thank you.

**Comment by DPTeamMember** [comment]
Hello @italolemos 

For now, I am closing the Issue.
You can open the issue and share details if you want.

Thank you.
