### ISSUE TITLE
Error installing version 2.0.0

### ISSUE THREAD

**Issue by anzolin** [DashboardPack/architectui-html-theme-free#31]
During the installation procedure of version 2.0.0, several vulnerabilities are found, not allowing the template to be generated.

Command executed: `npm audit report`

return:

ansi-regex  >2.1.1 <5.0.1
Severity: moderate
 Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix --force`
Will install node-sass@4.14.0, which is a breaking change
node_modules/sass-graph/node_modules/ansi-regex
  strip-ansi  4.0.0 - 5.2.0
  Depends on vulnerable versions of ansi-regex
  node_modules/sass-graph/node_modules/strip-ansi
    cliui  4.0.0 - 5.0.0
    Depends on vulnerable versions of strip-ansi
    Depends on vulnerable versions of wrap-ansi
    node_modules/sass-graph/node_modules/cliui
      yargs  10.1.0 - 15.0.0
      Depends on vulnerable versions of cliui
      Depends on vulnerable versions of string-width
      node_modules/sass-graph/node_modules/yargs
        sass-graph  2.2.5 || >=3.0.5
        Depends on vulnerable versions of yargs
        node_modules/sass-graph
          node-sass  >=4.14.1
          Depends on vulnerable versions of sass-graph
          node_modules/node-sass
    string-width  2.1.0 - 4.1.0
    Depends on vulnerable versions of strip-ansi
    node_modules/sass-graph/node_modules/string-width
      wrap-ansi  3.0.0 - 6.1.0
      Depends on vulnerable versions of string-width
      Depends on vulnerable versions of strip-ansi
      node_modules/sass-graph/node_modules/wrap-ansi

glob-parent  <5.1.2
Severity: high
Regular expression denial of service - https://github.com/advisories/GHSA-ww39-953v-wcq6
fix available via `npm audit fix`
node_modules/watchpack-chokidar2/node_modules/glob-parent
  chokidar  1.0.0-rc1 - 2.1.8
  Depends on vulnerable versions of glob-parent
  node_modules/watchpack-chokidar2/node_modules/chokidar
    watchpack-chokidar2  *
    Depends on vulnerable versions of chokidar
    node_modules/watchpack-chokidar2
      watchpack  1.7.2 - 1.7.5
      Depends on vulnerable versions of watchpack-chokidar2
      node_modules/watchpack
        webpack  4.44.0 - 4.46.0
        Depends on vulnerable versions of watchpack
        node_modules/webpack

13 vulnerabilities (8 moderate, 5 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

After executing the commands: `npm audit fix --force` and `npm install`, the template is not generated.

> What should I do to be able to generate the HTML's and the like?

**Comment by DPTeamMember** [comment]
Hello @anzolin 

You can instead of you the simple version of the template instead of the webpack one which is available in the download section of your order on our website or you can also download it from our git repo https://github.com/DashboardPack/architectui-html-pro

I will check the issue and resolve ASAP

Thank you

**Comment by DPTeamMember** [comment]
Hello @anzolin 

The fix is available in the new release, please check.

Thank you
