### ISSUE TITLE
Error when there is no calendar on the page

### ISSUE THREAD

**Issue by ptimouton** [DashboardPack/architectui-html-theme-free#36]
Everytime a page is loaded (appart from the calendar component demo page) this error occurs : 

> fullcalendar.js:15532 Uncaught TypeError: Cannot read properties of null (reading '__k')
>     at S (fullcalendar.js:15532:8111)
>     at fullcalendar.js:10210:81
>     at flushSync (fullcalendar.js:10338:5)
>     at Calendar._this.handleRenderRequest [as drainedOption] (fullcalendar.js:10209:80)
>     at DelayedRunner.drained (fullcalendar.js:7089:18)
>     at DelayedRunner.tryDrain (fullcalendar.js:7071:22)
>     at DelayedRunner.request (fullcalendar.js:7032:22)
>     at Calendar.render (fullcalendar.js:10249:27)
>     at HTMLDocument.<anonymous> (fullcalendar.js:15207:12)

fullcalendar.js -> this.renderRunner.request() is called even there is no calendar on the page.

Thank you :)

**Comment by DPTeamMember** [comment]
Hello there, 

Please update the fullcalendar library to resolve the error, I will release the fix soon.

Thank you

**Comment by DPTeamMember** [comment]
Hello @ptimouton 

Issue fix in the latest release please check.

Thank you.
