### ISSUE TITLE
In Mobile View the data grid is showing only First 3 Columns

### ISSUE THREAD

**Issue by gargabhisar** [DashboardPack/architectui-html-theme-free#37]
In Mobile View the data grid is showing only First 3 Columns, how can we make i scrollable to see all the columns ?

**Comment by DPTeamMember** [comment]
Hello @gargabhisar 

We checked the issue and it's working fine for us.
Please share the URL from the template live demo.
Please also share if the issue is with any specific device size.

Thank you.

**Comment by gargabhisar** [comment]
https://dashboardpack.com/live-demo-preview/?livedemo=290

this is the URL... Try opening it in Mobile View.
It is showing only 3 columns
![only 3 columns showing up](https://user-images.githubusercontent.com/23273356/193754907-9a0cb1b3-092f-4cb4-acdd-6c5f853ba0e8.png)

Where as it has 6 columns showing up in desktop view:
![it has 6 columns](https://user-images.githubusercontent.com/23273356/193755186-f47695e5-33bb-4626-866d-01eb738d7705.png)

**Comment by DPTeamMember** [comment]
Hello @gargabhisar 

Thanks for reporting the bug, will resolve it and share the solution soon.

Thank you.

**Comment by DPTeamMember** [comment]
Hello @gargabhisar 

The data table is responsive dear, Please click on the row on a small screen and it will expand with the remaining hidden columns.

Thank you.
