### ISSUE TITLE
Unable to download free html version

### ISSUE THREAD

**Issue by WhiteDragonD** [DashboardPack/architectui-html-theme-free#41]
Trying to download latest version from website, the url in the email does not work.

https://dashboardpack.com/wp-content/uploads/woocommerce_uploads/2019/01/architectui-html-free.zip

403 Forbidden
nginx

**Comment by optmsp** [comment]
Ditto. I provided my email address and then got a bad link. ?

**Comment by lexherd** [comment]
I've got the same problem

**Comment by hcroeze** [comment]
I have the same problem. Anyone got a solution yet?

**Comment by WhiteDragonD** [comment]
> I have the same problem. Anyone got a solution yet?

Looks like they don't care about supporting this template anymore, no replies, contact info, moved around to different websites....

I went to AdminLTE instead.

https://adminlte.io/
