### ISSUE TITLE
Where is /src/DemoPages/Main/index.js ?

### ISSUE THREAD

**Issue by tripler-codehub** [DashboardPack/architectui-html-theme-free#7]
There is a /src/DemoPages/Main/index.js in Layout Modifiers of Documentation but 
i can't found the /src/DemoPages/Main/index.js file
where is it?

**Comment by DPTeamMember** [comment]
Hello @tripler-codehub 

We don't have such a file in the Template dear, You are maybe mistaking something.

Thank you.
