### ISSUE TITLE
main.js:89 Error: <g> attribute transform: Expected number, "scale(NaN) translate(N…".

### ISSUE THREAD

**Issue by trigonometric-act** [DashboardPack/architectui-html-theme-free#9]
main.js:89 Error: <g> attribute transform: Expected number, "scale(NaN) translate(N…".

How to solve the error? thanks!

**Comment by rknidzam** [comment]
Hi, any solution for this issue?

**Comment by DPTeamMember** [comment]
Hello @rknidzam @trigonometric-act 

The issue is caused by jvectormap-next plugin. Will Update or replace the plugin in the next possible release.

Thank you.

**Comment by DPTeamMember** [comment]
Hello @rknidzam @trigonometric-act 

The issue has been resolved. 

Thank you.
